### ISSUE TITLE
'latest' redirect broken in firefox/IE

### ISSUE THREAD

**Issue by kevmoo** [astashov/dartdocs.org#28]
Try this in Firefox: https://www.dartdocs.org/documentation/string_scanner/latest/index.html

As mentioned here: https://twitter.com/antumbral/status/704768828513714176

**Comment by nex3** [comment]
This is a pretty serious issue. It means that any links that include "latest" are completely broken across the majority of browsers, and possibly have been for a while.

**Comment by kevmoo** [comment]
Also: please add a "Click here if you are not redirected" link to the body – just in case!

**Comment by astashov** [comment]
Aw, snap - FireFox doesn't redirect to meta refresh links by default - http://stackoverflow.com/questions/11908063/meta-refresh-not-working-in-firefox.

Could the link in the body solve it for now? Since it's just a static site on GCS, we cannot really return 302's, we'd need to introduce some sort of a proxy - it's not a quick fix.

**Comment by astashov** [comment]
Actually, will try to add overriding `document.location` on load, should help as well.

**Comment by astashov** [comment]
Safari and Chrome work, Firefox and IE11 - do not.

**Comment by astashov** [comment]
Fixed
