### ISSUE TITLE
[WIP] Link to angular_component API docs under webdev

### ISSUE THREAD

**Issue by chalin** [astashov/dartdocs.org#43]
Similar to #30, this is a request to redirect
- [dartdocs.org/documentation/angular2_components](https://www.dartdocs.org/documentation/angular2_components/0.4.1-alpha/index.html)

to:
- https://webdev.dartlang.org/components/api

cc @kwalrath

**Comment by chalin** [comment]
WIP. The new site isn't up quite yet but it will be shortly.

**Comment by chalin** [comment]
@kevmoo, @kwalrath - I'm having second thoughts. Maybe we can keep the ACX API docs under dartdocs.org since webdev will only host the latest version. WDYT?

@astashov - maybe only the latest can be redirected?

(If so, and if all agree to the above, then we could do the same for the angular API docs.)

**Comment by filiph** [comment]
Yeah, for docs I think we should still use dartdocs. But lets link to https://webdev.dartlang.org/components/ prominently from the package's README.

**Comment by chalin** [comment]
Ok, good. I'll let @kwalrath chime in before (possibly) closing this issue.

**Comment by kwalrath** [comment]
I guess the reason I wanted the angular_components API docs on webdev was because it was surprising to me not to be able to find them using the webdev site search. I might be able to work around that, though, by changing the search engine.

Let's close this (for now, at least).

As for the angular API docs, we hosted those because they just weren't working on dartdocs.org. But that's a separate issue.
